=== lucasthierry9/pos-2026-tarefas/tarefa06/quiz.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:a="http://quiz.org"
        targetNamespace="http://quiz.org"
        elementFormDefault="qualified">
        <element name="quiz">
            <complexType>
                <sequence>
                    <element ref="a:disciplina"/>
                    <element ref="a:professor"/>
                    <element ref="a:turma"/>
                    <element ref="a:data"/>
                    <element ref="a:questões" minOccurs="1" maxOccurs="unbounded"/>
                </sequence>
            </complexType>
        </element>

        <element name="professor">
            <complexType>
                <sequence>
                    <element ref="a:nome"/>
                    <element ref="a:matrícula"/>
                </sequence>
            </complexType>
        </element>

        <complexType name="questões">
            <sequence>
                <element ref="a:questão" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>

        <element name="questão">
            <complexType>
                <sequence>
                    <element ref="a:enunciado"/>
                    <element ref="a:pontuação"/>
                    <element ref="a:alternativas"/>
                </sequence>
            </complexType>
        </element>

        <element name="alternativas">
            <complexType>
                <sequence>
                    <element ref="a:alternativa" minOccurs="1" maxOccurs="unbounded"/>
                </sequence>
            </complexType>
        </element>

        <element name="alternativa">
            <complexType>
                <simpleContent>
                    <extension base="string">
                        <attribute name="correta" type="string" use="required"/>
                    </extension>
                </simpleContent>
            </complexType>
        </element>

        <element name="disciplina" type="string"/>
        <element name="nome" type="string"/>
        <element name="matrícula" type="string"/>
        <element name="turma" type="string"/>
        <element name="data" type="string"/>
        <element name="questões" type="a:questões"/>
        <element name="enunciado" type="string"/>
        <element name="pontuação" type="integer"/>
</schema>

=== lucasthierry9/pos-2026-tarefas/tarefa06/quiz.xml
<?xml version="1.0" encoding="utf-8"?>
<quiz xmlns="http://quiz.org" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://quiz.org quiz.xsd">
    <disciplina>POS</disciplina>

    <professor>
        <nome>Mauricio Freire</nome>
        <matrícula>536784</matrícula>
    </professor>

    <turma>Infoweb 3M</turma>
    <data>2026-08-21</data>

    <questões>
        <questão>
            <enunciado>Qual é o significado da sigla POS?</enunciado>
            <pontuação>2</pontuação>
            <alternativas>
                <alternativa correta="sim">Programação Orientada a Serviços</alternativa>
                <alternativa correta="nao">Programação Orientada a Sistemas</alternativa>
                <alternativa correta="nao">Processo Operacional de Software</alternativa>
                <alternativa correta="nao">Plataforma Operacional de Serviços</alternativa>
            </alternativas>
        </questão>
        <questão>
            <enunciado>Qual é o principal objetivo da Programação Orientada a Serviços?</enunciado>
            <pontuação>2</pontuação>
            <alternativas>
                <alternativa correta="nao">Usar apenas programação orientada a objetos</alternativa>
                <alternativa correta="nao">Criar programas muito rápidos e leves</alternativa>
                <alternativa correta="sim">Dividir o sistema em pequenos serviços independentes e reutilizáveis</alternativa>
                <alternativa correta="nao">Evitar o uso de redes na comunicação entre sistemas</alternativa>
            </alternativas>
        </questão>
        <questão>
            <enunciado>Em POS, os serviços se comunicam principalmente por meio de:</enunciado>
            <pontuação>2</pontuação>
            <alternativas>
                <alternativa correta="sim">Requisições pela rede usando protocolo como HTTP</alternativa>
                <alternativa correta="nao">Chamadas diretas de memória (RAM)</alternativa>
                <alternativa correta="nao">Arquivos locais compartilhados</alternativa>
                <alternativa correta="nao">Cabos USB entre servidores</alternativa>
            </alternativas>
        </questão>
        <questão>
            <enunciado>Qual das opções abaixo é uma caracteristícas da POS?</enunciado>
            <pontuação>2</pontuação>
            <alternativas>
                <alternativa correta="nao">Sistema funcionando apenas em um único computador.</alternativa>
                <alternativa correta="nao">Baixa reutilização</alternativa>
                <alternativa correta="nao">Forte depência entre os módulos</alternativa>
                <alternativa correta="sim">Serviços independentes que podem ser usados por diferentes sistemas.</alternativa>
            </alternativas>
        </questão>
        <questão>
            <enunciado>Qual a tecnologia é comumente utilizada para implementar a comunicação entre serviços em POS?</enunciado>
            <pontuação>2</pontuação>
            <alternativas>
                <alternativa correta="sim">API Web (REST)</alternativa>
                <alternativa correta="nao">USB</alternativa>
                <alternativa correta="nao">Bluetooth</alternativa>
                <alternativa correta="nao">HDMI</alternativa>
            </alternativas>
        </questão>
    </questões>
</quiz>
